<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <UseWPF>true</UseWPF>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../LongJumpReplay.Core/LongJumpReplay.Core.csproj" />
    <ProjectReference Include="../LongJumpReplay.Video.Windows/LongJumpReplay.Video.Windows.csproj" />
    <ProjectReference Include="../LongJumpReplay.Infrastructure/LongJumpReplay.Infrastructure.csproj" />
  </ItemGroup>
</Project>
