"""Email-based activation against the licensing API.

The customer enters the email address they bought with, receives a code, and
this module exchanges that for a signed authorization which `authorization.py`
then verifies locally. No licence key is involved.

Networking uses urllib so the frozen build gains no new dependency, matching the
approach already taken in `trial.py`.
"""

from __future__ import annotations

import hashlib
import json
import os
import platform
import sys
import uuid
from dataclasses import dataclass
from typing import Any, Callable
from urllib.error import HTTPError, URLError
from urllib.request import Request, urlopen

from .authorization import (
    load_authorization,
    save_authorization,
    should_refresh,
    verify_authorization,
)

API_BASE = os.environ.get("LJR_LICENSE_API_URL", "https://api.tomaspisar.cz").rstrip("/")
REQUEST_TIMEOUT = 15


def _windows_machine_guid() -> str | None:
    """Read Windows' own installation GUID.

    This is the most stable identifier available: it survives network adapter
    changes, docking stations and hostname changes, all of which break the
    legacy `machine_code()`. It is regenerated by a Windows reinstall, which is
    the documented case where a customer must re-activate.
    """
    if sys.platform != "win32":
        return None
    try:
        import winreg

        with winreg.OpenKey(
            winreg.HKEY_LOCAL_MACHINE,
            r"SOFTWARE\Microsoft\Cryptography",
            0,
            winreg.KEY_READ | getattr(winreg, "KEY_WOW64_64KEY", 0),
        ) as key:
            value, _ = winreg.QueryValueEx(key, "MachineGuid")
            return str(value) if value else None
    except OSError:
        return None


def device_id() -> str:
    """A stable pseudonymous identifier for this computer.

    Only this derived value is ever sent to the server - never the raw GUID,
    MAC address or computer name. It is a one-way hash, so the server cannot
    recover hardware details from it.

    Behaviour:
      * Windows reinstall      -> changes (MachineGuid is regenerated)
      * Hardware changes       -> unchanged (does not depend on the network card)
      * Docking station        -> unchanged
      * Application reinstall  -> unchanged
      * Different computer     -> changes
      * Non-Windows / no GUID  -> falls back to host and MAC, which is less
                                  stable; this is a Windows product, so the
                                  fallback exists only so the code runs in tests
                                  and on developer machines.

    This is deliberately not a claim of perfect hardware identity. It is a
    reasonable, privacy-preserving approximation, and the server-side device
    limit is what actually enforces the licence.
    """
    guid = _windows_machine_guid()
    if guid:
        material = f"ljr-v2|windows|{guid}"
    else:
        material = "|".join(
            ["ljr-v2", platform.system(), platform.node(), str(uuid.getnode())]
        )
    digest = hashlib.sha256(material.encode("utf-8")).digest()
    # base64url-ish alphabet, 43 chars: satisfies the server's
    # ^[A-Za-z0-9_-]{16,128}$ without any padding characters.
    import base64

    return base64.urlsafe_b64encode(digest).decode("ascii").rstrip("=")


def device_name() -> str | None:
    """A human label so the owner can tell their own computers apart."""
    name = platform.node()
    return name[:64] if name else None


class ActivationError(Exception):
    """Carries a message already suitable for showing to the customer."""

    def __init__(self, message: str, code: str = "error") -> None:
        super().__init__(message)
        self.code = code


def _post(path: str, payload: dict[str, Any], opener: Callable[..., Any] = urlopen) -> dict[str, Any]:
    request = Request(
        f"{API_BASE}{path}",
        data=json.dumps(payload).encode("utf-8"),
        headers={"Content-Type": "application/json", "Accept": "application/json",
                 "User-Agent": "LongJumpReplay-activation/1"},
        method="POST",
    )
    try:
        with opener(request, timeout=REQUEST_TIMEOUT) as response:
            return json.loads(response.read().decode("utf-8"))
    except HTTPError as error:
        try:
            body = json.loads(error.read().decode("utf-8"))
        except Exception:  # noqa: BLE001 - a non-JSON error body is still an error
            raise ActivationError("The licensing server returned an unexpected response.") from error
        raise ActivationError(
            str(body.get("message") or "The licensing server rejected the request."),
            str(body.get("error") or "error"),
        ) from error
    except (URLError, TimeoutError, OSError) as error:
        raise ActivationError(
            "Could not reach the licensing server. Check your internet connection and try again.",
            "offline",
        ) from error
    except (ValueError, json.JSONDecodeError) as error:
        raise ActivationError("The licensing server returned an unreadable response.") from error


def request_code(email: str, opener: Callable[..., Any] = urlopen) -> int:
    """Ask for a verification code. Returns how many minutes it stays valid."""
    data = _post("/api/license/request-code", {"email": email}, opener)
    return int(data.get("expires_in_minutes") or 10)


def verify_code(email: str, code: str, opener: Callable[..., Any] = urlopen) -> str:
    """Exchange the emailed code for a single-use activation grant."""
    data = _post("/api/license/verify-code", {"email": email, "code": code}, opener)
    grant = data.get("activation_grant")
    if not isinstance(grant, str) or not grant:
        raise ActivationError("The licensing server did not return an activation.")
    return grant


@dataclass
class ActivationResult:
    license_type: str
    max_devices: int
    authorization: str


def activate(grant: str, opener: Callable[..., Any] = urlopen) -> ActivationResult:
    """Activate this computer and store the returned authorization."""
    data = _post(
        "/api/license/activate",
        {"activation_grant": grant, "machine_id": device_id(), "device_name": device_name()},
        opener,
    )
    token = data.get("authorization")
    if not isinstance(token, str):
        raise ActivationError("The licensing server did not return an authorization.")

    valid, reason, _ = verify_authorization(token, device_id())
    if not valid:
        # Refuse to store something the app cannot verify - that would produce a
        # licence that looks activated but fails on the next start.
        raise ActivationError(f"The authorization could not be verified ({reason}).", reason)

    save_authorization(token)
    return ActivationResult(
        license_type=str(data.get("license_type") or "unknown"),
        max_devices=int(data.get("max_devices") or 0),
        authorization=token,
    )


def deactivate_this_computer(grant: str, opener: Callable[..., Any] = urlopen) -> bool:
    data = _post(
        "/api/license/deactivate-device",
        {"activation_grant": grant, "machine_id": device_id()},
        opener,
    )
    return bool(data.get("deactivated"))


def refresh(license_id: str, opener: Callable[..., Any] = urlopen) -> bool:
    """Periodic re-verification. Returns True when a fresh authorization was stored."""
    data = _post(
        "/api/license/verify", {"license_id": license_id, "machine_id": device_id()}, opener
    )
    token = data.get("authorization")
    if not isinstance(token, str):
        return False
    valid, _, _ = verify_authorization(token, device_id())
    if not valid:
        return False
    save_authorization(token)
    return True


def current_authorization() -> tuple[bool, str, dict[str, object] | None]:
    """Verify the stored authorization without touching the network."""
    token = load_authorization()
    if not token:
        return False, "authorization.missing", None
    return verify_authorization(token, device_id())


def refresh_if_due(opener: Callable[..., Any] = urlopen) -> None:
    """Renew in the background when past halfway through the window.

    Deliberately silent: a laptop that is offline must keep working, so a failed
    refresh is not an error until the authorization actually expires.
    """
    valid, _, payload = current_authorization()
    if not valid or not payload or not should_refresh(payload):
        return
    license_id = payload.get("license_id")
    if isinstance(license_id, str):
        try:
            refresh(license_id, opener)
        except ActivationError:
            pass
